# Generated by Django 4.2.6 on 2024-01-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceWeb', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
