# Generated by Django 4.2.6 on 2024-01-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceWeb', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
